version: 0.2

phases:
install:
runtime-versions:
dotnet: 8.x
pre_build:
commands:
- echo Restoring dependencies

- dotnet restore ./backend/dating-app.sln

build:
commands:
- echo Build started on `date`

- dotnet publish ./backend/dating-app.sln -c Release -o ./myapp

post_build:
commands:
- echo Build completed on `date`


artifacts:
files:
- '**/*'

base-directory: './myapp'

cache:
paths:
- '/root/.nuget/packages/**/*'