name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - feature/azure-storage
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - feature/azure-storage

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'  # Use the appropriate Node.js version for your Angular app
      - name: Install Dependencies
        run: |
          cd client
          npm install --legacy-peer-deps
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_YELLOW_DUNE_0AD40740F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "client"
          output_location: "client/dist/client/browser"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_YELLOW_DUNE_0AD40740F }}
          action: "close"
