name: AWS => Build, deploy, ASP.Net Core / api app to AWS ElasticBeanstalk - da-api-prod

on:
  push:
    branches:
      - feature/aws-prod
    paths:
      - 'backend/**'
      
  pull_request:
      branches:
      - feature/aws-prod
      paths:
      - 'backend/**'

  workflow_dispatch: # This line adds the manual trigger option

env:
WEBAPP_PACKAGE_PATH: ./publish

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      - name: dotnet publish
        run: dotnet publish ./backend/dating-app.sln -c Release -o ${{env.DOTNET_ROOT}}

      - name: Zip the application
        run: cd ${{env.DOTNET_ROOT}}; zip -r ../myapp.zip .; cd ..

      - name: Upload zipped artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: 'da-api'
          environment_name: 'production'
          version_label: ${{ github.sha }}
          region: 'us-east-1'
          deployment_package: myapp.zip
      

  cleanup:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Clean up artifacts and publish directory
        uses: actions/checkout@v4
        with:
          clean: true
